services:
  cleaner:
    build:
      context: .
      dockerfile: Dockerfile.cleaner
    volumes:
      - ./audio:/usr/src/app/audio
      - ./settings.json:/usr/src/app/settings.json
    environment:
      - TZ=Europe/Amsterdam
  peakfilegenerator:
    build:
      context: .
      dockerfile: Dockerfile.peakfilegenerator
    volumes:
      - ./audio:/usr/src/app/audio
      - ./settings.json:/usr/src/app/settings.json
    environment:
      - TZ=Europe/Amsterdam
  recorder:
    build:
      context: .
      dockerfile: Dockerfile.recorder
    volumes:
      - ./audio:/usr/src/app/audio
      - ./settings.json:/usr/src/app/settings.json
    environment:
      - TZ=Europe/Amsterdam
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./audio:/usr/src/app/audio
      - ./settings.json:/usr/src/app/settings.json
    ports:
      - "${PORT}:80"
    environment:
      - TZ=Europe/Amsterdam
      - PORT=${PORT}
    networks:
      - web-network
networks:
  web-network:
